### ISSUE TITLE
Could not install package 'Exira.EventStore 0.3.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### ISSUE THREAD

**Issue by jorgedfbranco** [exira/ges#1]
I'm using Visual Studio Community Edition 2015.

**Comment by CumpsD** [comment]
The nuget package was only targeting .NET 4.6

I've built a version now for 4.5, 4.5.2 and 4.6

Can you try again with version 0.4.9? https://www.nuget.org/packages/Exira.EventStore/0.4.9

**Comment by jorgedfbranco** [comment]
It resolves correctly now, thanks.

**Comment by CumpsD** [comment]
I'll make the same changes to ges-owin too, in case you need it in the future :)
